name: Deploy Landing Page to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
      
      - name: Build Vite app
        run: npm run build
        env:
          NODE_ENV: production
          VITE_APP_VERSION: ${{ github.sha }}
      
      - name: Create .env file if needed
        run: |
          touch .env
          # Add environment variables here when needed
          echo "VITE_API_URL=https://api.graviitalbeats.com" >> .env
          echo "VITE_APP_VERSION=${{ github.sha }}" >> .env
        
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/,package.json,.env"
          target: "/var/www/landing.graviitalbeats.com"
          strip_components: 0
          overwrite: true
          
      # This step ensures images directory is properly copied to the server
      - name: Deploy public images
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "public/images/"
          target: "/var/www/landing.graviitalbeats.com/images"
          strip_components: 2
          overwrite: true
      
   